#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run test

branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'master' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed! / Commit langsung ke branch master dilarang!\n" && exit 1
fi